from src import DEVS, DRAGONS, DEMONS, TIGERS, WOLVES, telethn

IMMUNE_USERS = DRAGONS + WOLVES + DEMONS + TIGERS + DEVS

IMMUNE_USERS = (
    list(DRAGONS) + list(WOLVES) + list(DEMONS) + list(TIGERS) + list(DEVS)
)
